version: "2"

services:

  # uwsgi is the ltd-keeper app run by uWSGI
  uwsgi:
    # comment out `build` field to use a pre-built Docker Hub image
    build:
      context: .
    image: lsstsqre/ltd-keeper:latest
    expose:
      - "3031"

  # nginx acts as a reverse proxy for the uWSGI+python web app container
  # This container is configured to forward traffic to http://uwsgi:3031
  nginx:
    # Un-comment the 'build' key to instead rebuild nginx-python from source.
    # Build assumes that https://github.com/lsst-sqre/nginx-python-docker
    # is cloned along side the ltd-keeper repo.
    # build:
    #   context: "../nginx-python-docker/compose"
    image: lsstsqre/nginx-python:compose
    ports:
      - "80:80"
    links:
      - uwsgi
