# Load balancer service for Keeper pods
#
# See http://kubernetes.io/docs/user-guide/services/#type-loadbalancer
#
# This Service internally load balances traffic from the nginx-ssl-proxy
# to pods on the 'keeper' selector.

apiVersion: v1
kind: Service
metadata:
  name: keeper
  labels:
    name: keeper
spec:
  ports:
    - name: http
      port: 8080
      targetPort: keeper-nginx
      protocol: TCP
  selector:
    name: keeper
